name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

# Unittestの結果を表示する際にこの設定がないと権限エラーが出ます。
permissions: write-all

env:
  FLUTTER_VERSION: 3.19.0

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Install Flutter Testing Library
        run: flutter pub global activate junitreport

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test -r json --coverage | tojunit --output TEST-results.xml

      - name: Cache Workspace with Results
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: workspace-with-results-${{ github.sha }}

  notification:
    name: Send Notification
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Workspace Cache from Test Job
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}
          key: workspace-with-results-${{ github.sha }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: TEST-results.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
